const categories=['cpu','gpu','motherboard','ram','case','psu','storage','cooler','fans'];
const labels={cpu:'CPU',gpu:'GPU',motherboard:'Motherboard',ram:'RAM',case:'Case',psu:'Power supply',storage:'Storage',cooler:'CPU cooler',fans:'Case fans'};
const baseParts=[
{id:'cpu-r5-7600',type:'cpu',name:'AMD Ryzen 5 7600',price:199,power:65,score:132,socket:'AM5',coolerNeed:120,brand:'AMD',spec:'6 cores • AM5'},
{id:'cpu-r7-7800x3d',type:'cpu',name:'AMD Ryzen 7 7800X3D',price:349,power:120,score:190,socket:'AM5',coolerNeed:180,brand:'AMD',spec:'8 cores • AM5'},
{id:'cpu-r9-9950x',type:'cpu',name:'AMD Ryzen 9 9950X',price:649,power:170,score:240,socket:'AM5',coolerNeed:240,brand:'AMD',spec:'16 cores • AM5'},
{id:'cpu-i5-14600k',type:'cpu',name:'Intel Core i5-14600K',price:269,power:181,score:170,socket:'LGA1700',coolerNeed:200,brand:'Intel',spec:'14 cores • LGA1700'},
{id:'cpu-i7-14700k',type:'cpu',name:'Intel Core i7-14700K',price:369,power:253,score:215,socket:'LGA1700',coolerNeed:280,brand:'Intel',spec:'20 cores • LGA1700'},
{id:'gpu-rx7600',type:'gpu',name:'Radeon RX 7600',price:269,power:165,score:95,length:269,brand:'AMD',spec:'8 GB • 269 mm'},
{id:'gpu-rx7800xt',type:'gpu',name:'Radeon RX 7800 XT',price:499,power:263,score:176,length:280,brand:'AMD',spec:'16 GB • 280 mm'},
{id:'gpu-rx7900xtx',type:'gpu',name:'Radeon RX 7900 XTX',price:899,power:355,score:245,length:287,brand:'AMD',spec:'24 GB • 287 mm'},
{id:'gpu-4060',type:'gpu',name:'GeForce RTX 4060',price:299,power:115,score:100,length:244,brand:'NVIDIA',spec:'8 GB • 244 mm'},
{id:'gpu-4070s',type:'gpu',name:'GeForce RTX 4070 SUPER',price:599,power:220,score:178,length:267,brand:'NVIDIA',spec:'12 GB • 267 mm'},
{id:'gpu-4080s',type:'gpu',name:'GeForce RTX 4080 SUPER',price:999,power:320,score:238,length:304,brand:'NVIDIA',spec:'16 GB • 304 mm'},
{id:'mb-b650',type:'motherboard',name:'B650 Gaming WiFi',price:179,power:45,socket:'AM5',ramType:'DDR5',form:'ATX',ramSlots:4,brand:'Nova',spec:'AM5 • DDR5 • ATX'},
{id:'mb-x670',type:'motherboard',name:'X670E Creator',price:329,power:55,socket:'AM5',ramType:'DDR5',form:'ATX',ramSlots:4,brand:'Nova',spec:'AM5 • DDR5 • ATX'},
{id:'mb-b760',type:'motherboard',name:'B760M Pro',price:139,power:40,socket:'LGA1700',ramType:'DDR5',form:'mATX',ramSlots:4,brand:'Forge',spec:'LGA1700 • DDR5 • mATX'},
{id:'mb-z790',type:'motherboard',name:'Z790 Elite WiFi',price:279,power:58,socket:'LGA1700',ramType:'DDR5',form:'ATX',ramSlots:4,brand:'Forge',spec:'LGA1700 • DDR5 • ATX'},
{id:'ram-16-5200',type:'ram',name:'16 GB DDR5-5200',price:49,power:6,ramType:'DDR5',capacity:16,score:90,brand:'Pulse',spec:'16 GB • DDR5-5200'},
{id:'ram-32-6000',type:'ram',name:'32 GB DDR5-6000',price:89,power:8,ramType:'DDR5',capacity:32,score:118,brand:'Pulse',spec:'32 GB • DDR5-6000'},
{id:'ram-64-6400',type:'ram',name:'64 GB DDR5-6400',price:179,power:12,ramType:'DDR5',capacity:64,score:128,brand:'Pulse',spec:'64 GB • DDR5-6400'},
{id:'case-air-mini',type:'case',name:'Airflow Mini',price:69,power:0,forms:['mATX','ITX'],gpuMax:300,coolerMax:160,brand:'Frame',spec:'mATX • GPU 300 mm'},
{id:'case-air-atx',type:'case',name:'Airflow ATX',price:109,power:0,forms:['ATX','mATX','ITX'],gpuMax:360,coolerMax:180,brand:'Frame',spec:'ATX • GPU 360 mm'},
{id:'case-tower',type:'case',name:'Panorama Full Tower',price:189,power:0,forms:['EATX','ATX','mATX','ITX'],gpuMax:420,coolerMax:195,brand:'Frame',spec:'E-ATX • GPU 420 mm'},
{id:'psu-550',type:'psu',name:'550 W Bronze PSU',price:59,power:0,wattage:550,brand:'Volt',spec:'550 W • 80+ Bronze'},
{id:'psu-750',type:'psu',name:'750 W Gold PSU',price:99,power:0,wattage:750,brand:'Volt',spec:'750 W • 80+ Gold'},
{id:'psu-1000',type:'psu',name:'1000 W Platinum PSU',price:179,power:0,wattage:1000,brand:'Volt',spec:'1000 W • 80+ Platinum'},
{id:'ssd-1tb',type:'storage',name:'1 TB NVMe SSD',price:69,power:6,capacity:1000,score:100,brand:'Flash',spec:'1 TB • 5,000 MB/s'},
{id:'ssd-2tb',type:'storage',name:'2 TB Gen4 NVMe SSD',price:119,power:8,capacity:2000,score:125,brand:'Flash',spec:'2 TB • 7,400 MB/s'},
{id:'ssd-4tb',type:'storage',name:'4 TB Gen5 NVMe SSD',price:299,power:12,capacity:4000,score:150,brand:'Flash',spec:'4 TB • 12,000 MB/s'},
{id:'cooler-stock',type:'cooler',name:'Compact Air Cooler',price:29,power:4,capacity:120,height:150,brand:'Frost',spec:'120 W • 150 mm'},
{id:'cooler-twin',type:'cooler',name:'Twin Tower Air Cooler',price:69,power:7,capacity:220,height:165,brand:'Frost',spec:'220 W • 165 mm'},
{id:'cooler-aio',type:'cooler',name:'360 mm Liquid Cooler',price:139,power:15,capacity:320,height:40,brand:'Frost',spec:'320 W • 360 mm radiator'},
{id:'fans-2',type:'fans',name:'2 × 120 mm Fans',price:24,power:5,count:2,cooling:20,brand:'Breeze',spec:'2 fans • Quiet'},
{id:'fans-4',type:'fans',name:'4 × 140 mm Fans',price:59,power:11,count:4,cooling:45,brand:'Breeze',spec:'4 fans • High airflow'},
{id:'fans-rgb',type:'fans',name:'6 × RGB Fans',price:99,power:18,count:6,cooling:60,brand:'Breeze',spec:'6 fans • RGB'}
];
let parts=[...baseParts],active='cpu',selected=null,build={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function init(){renderCategories();renderParts();renderGames();bind();restore();updateAll();}
function renderCategories(){const c=$('#categories');c.innerHTML='';categories.forEach(type=>{const b=document.createElement('button');b.className='category'+(type===active?' active':'');b.textContent=labels[type];b.onclick=()=>{active=type;renderCategories();renderParts()};c.appendChild(b)})}
function renderParts(){const q=$('#search').value.trim().toLowerCase();const list=parts.filter(p=>p.type===active&&(!q||`${p.name} ${p.brand} ${p.spec}`.toLowerCase().includes(q)));$('#parts').innerHTML='';list.forEach(p=>{const el=document.createElement('article');el.className='part-card'+(selected?.id===p.id?' selected':'');el.draggable=true;el.dataset.id=p.id;el.innerHTML=`<div class="part-art">${labels[p.type]}</div><div><strong>${p.name}</strong><small>${p.brand||'Generic'} • ${p.spec||''}</small></div><div class="price">${money(p.price||0)}</div>`;el.addEventListener('dragstart',e=>{selected=p;e.dataTransfer.setData('text/plain',p.id)});el.onclick=()=>{selected=p;renderParts();$('#tip').textContent=`Selected ${p.name}. Tap the ${labels[p.type]} slot to install it.`};$('#parts').appendChild(el)});$('#partCount').textContent=`${parts.length} parts`}
function bind(){
$('#search').addEventListener('input',renderParts);$('#resetBtn').onclick=()=>{if(confirm('Remove every installed part?')){build={};selected=null;save();updateAll()}};
$('#tutorialBtn').onclick=()=>$('#tutorialDialog').showModal();$('#closeTutorial').onclick=()=>$('#tutorialDialog').close();
$$('.dropzone').forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('drag-over')});z.addEventListener('dragleave',()=>z.classList.remove('drag-over'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('drag-over');install(e.dataTransfer.getData('text/plain'),z.dataset.slot)});z.addEventListener('click',e=>{e.stopPropagation();if(selected)install(selected.id,z.dataset.slot)})});
$('#runBenchmark').onclick=benchmark;$('#loadRemoteBtn').onclick=loadRemote;['game','resolution','preset'].forEach(id=>$('#'+id).onchange=()=>{$('#fps').textContent='—'});
}
function install(id,slot){const p=parts.find(x=>x.id===id);if(!p)return;if(p.type!==slot){$('#tip').textContent=`${p.name} belongs in the ${labels[p.type]} slot, not ${labels[slot]}.`;return}build[slot]=p;selected=null;save();updateAll();renderParts();$('#tip').textContent=`Installed ${p.name}.`}
function remove(type){delete build[type];save();updateAll()}
function issues(){const e=[],w=[];const {cpu,motherboard:mb,ram,case:cs,gpu,psu,cooler,fans}=build;const draw=powerDraw();if(cpu&&mb&&cpu.socket!==mb.socket)e.push(`CPU socket ${cpu.socket} does not match motherboard socket ${mb.socket}.`);if(ram&&mb&&ram.ramType!==mb.ramType)e.push(`${ram.ramType} memory does not match the motherboard's ${mb.ramType} slots.`);if(cs&&mb&&!cs.forms.includes(mb.form))e.push(`${mb.form} motherboard does not fit in this case.`);if(cs&&gpu&&gpu.length>cs.gpuMax)e.push(`GPU is ${gpu.length} mm, but the case allows ${cs.gpuMax} mm.`);if(cs&&cooler&&cooler.height>cs.coolerMax)e.push(`Cooler is ${cooler.height} mm tall, but the case allows ${cs.coolerMax} mm.`);if(cpu&&cooler&&cooler.capacity<cpu.coolerNeed)e.push(`Cooler capacity is too low for this CPU (${cooler.capacity} W vs ${cpu.coolerNeed} W recommended).`);if(psu&&psu.wattage<draw*1.2)e.push(`PSU needs more headroom: ${psu.wattage} W installed, about ${Math.ceil(draw*1.2)} W recommended.`);if(!fans)w.push('No case fans installed; temperatures may be higher.');if(build.storage&&build.storage.capacity<1000)w.push('Less than 1 TB of storage may fill quickly.');return{e,w}}
function powerDraw(){return 35+Object.values(build).reduce((s,p)=>s+(Number(p.power)||0),0)}
function updateAll(){const installed=Object.keys(build).length;const {e,w}=issues();$('#cost').textContent=money(Object.values(build).reduce((s,p)=>s+(Number(p.price)||0),0));$('#power').textContent=`${powerDraw()} W`;$('#progress').textContent=`${Math.round(installed/categories.length*100)}%`;const status=installed<categories.length?'Incomplete':e.length?'Conflicts':'Compatible';$('#compat').textContent=status;$('#compat').style.color=e.length?'var(--bad)':installed===categories.length?'var(--good)':'var(--warn)';$$('.dropzone').forEach(z=>{const p=build[z.dataset.slot];z.classList.toggle('installed',!!p);z.classList.remove('invalid');const span=z.querySelector('span');if(span)span.textContent=p?p.name:labels[z.dataset.slot]?.toUpperCase()||'CASE'});if(e.length){$('#compatDetails').className='compat-details bad';$('#compatDetails').innerHTML='<strong>Compatibility problems</strong><br>'+e.map(x=>'• '+x).join('<br>')}else if(w.length){$('#compatDetails').className='compat-details warn';$('#compatDetails').innerHTML='<strong>No hard conflicts</strong><br>'+w.map(x=>'• '+x).join('<br>')}else{$('#compatDetails').className='compat-details good';$('#compatDetails').textContent=installed===categories.length?'Build is complete and compatible.':'No conflicts detected so far.'}renderBuildList()}
function renderBuildList(){const root=$('#buildList');root.innerHTML='';categories.forEach(type=>{const p=build[type];const el=document.createElement('div');el.className='build-item';el.innerHTML=`<span>${labels[type]}</span><strong>${p?p.name:'Empty'}</strong>`;if(p){el.title='Tap to remove';el.onclick=()=>remove(type)}root.appendChild(el)})}
const games={Minecraft:{cpu:.62,gpu:.38,base:390},Fortnite:{cpu:.42,gpu:.58,base:245},'Cyberpunk 2077':{cpu:.28,gpu:.72,base:112},'Counter-Strike 2':{cpu:.67,gpu:.33,base:410},'Forza Horizon 5':{cpu:.30,gpu:.70,base:160},'Roblox':{cpu:.60,gpu:.40,base:300}};
function renderGames(){Object.keys(games).forEach(g=>$('#game').add(new Option(g,g)))}
function benchmark(){const {cpu,gpu,ram,cooler,fans}=build;const {e}=issues();if(!cpu||!gpu){alert('Install both a CPU and GPU first.');return}const g=games[$('#game').value],res={1080:1,1440:.73,'4k':.43}[$('#resolution').value],preset={low:1.28,medium:1.12,high:1,ultra:.82}[$('#preset').value];const cpuFactor=cpu.score/170,gpuFactor=gpu.score/175;let fps=g.base*(cpuFactor*g.cpu+gpuFactor*g.gpu)*res*preset;fps*=ram?.capacity>=32?1.04:ram?.capacity>=16?1:0.86;if(e.length)fps*=.72;fps=Math.max(12,Math.round(fps));const cpuLimit=cpuFactor*g.cpu<gpuFactor*g.gpu;const temp=Math.round(86-(cooler?.capacity||80)/18-(fans?.cooling||0)/12+(cpu.power||65)/35);$('#fps').textContent=fps;$('#low').textContent=Math.round(fps*.78);$('#bottleneck').textContent=cpuLimit?'CPU':'GPU';$('#temperature').textContent=`${Math.max(45,Math.min(99,temp))} °C`;$('#noise').textContent=(fans?.count||0)>=4?'Moderate':cooler?.capacity>250?'Moderate':'Quiet / warm'}
async function loadRemote(){const url=$('#remoteUrl').value.trim();if(!url)return alert('Enter a JSON URL first.');const btn=$('#loadRemoteBtn');btn.disabled=true;btn.textContent='Loading…';try{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();const incoming=Array.isArray(data)?data:data.parts;if(!Array.isArray(incoming))throw new Error('JSON must be an array or contain a parts array.');const valid=incoming.filter(p=>p&&categories.includes(p.type)&&p.name).map((p,i)=>({...p,id:p.id||`remote-${Date.now()}-${i}`,price:Number(p.price)||0,power:Number(p.power)||0,spec:p.spec||'Remote catalog part'}));parts=[...baseParts,...valid];renderParts();alert(`Loaded ${valid.length} remote parts.`)}catch(err){alert(`Could not load catalog: ${err.message}`)}finally{btn.disabled=false;btn.textContent='Load internet catalog'}}
function save(){localStorage.setItem('silicon-workshop-build',JSON.stringify(Object.fromEntries(Object.entries(build).map(([k,v])=>[k,v.id]))))}
function restore(){try{const ids=JSON.parse(localStorage.getItem('silicon-workshop-build')||'{}');for(const [k,id] of Object.entries(ids)){const p=parts.find(x=>x.id===id);if(p)build[k]=p}}catch{build={}}}
init();
